version: '3.7'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  editor:
    image: ghcr.io/serlo/serlo-editor-for-edusharing:main
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    env_file:
      - .env
      - .env.plattform_id
    extra_hosts:
      - "host.docker.internal:host-gateway"
