version: '3.7'

services:

  repository-search-elastic-index:
    image: "community/edu_sharing-community-repository-plugin-elastic-deploy-docker-build-elasticsearch:maven-feature-ltiplatform-8.1-SNAPSHOT"
    environment:
      ES_JAVA_OPTS: >-
        -Xms${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMS:-512m}
        -Xmx${REPOSITORY_SEARCH_ELASTIC_INDEX_JAVA_XMX:-512m}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      xpack.security.enabled: "false"
    expose:
      - "7199"
      - "9200"
      - "9300"
    volumes:
      - "repository-search-elastic-index-volume:/usr/share/elasticsearch/data"

  repository-search-elastic-tracker:
    image: "community/edu_sharing-community-repository-plugin-elastic-deploy-docker-build-tracker:maven-feature-ltiplatform-8.1-SNAPSHOT"
    command:
      - -Xms${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMS:-512m}
      - -Xmx${REPOSITORY_SEARCH_ELASTIC_TRACKER_JAVA_XMX:-512m}
      - -Dcom.sun.management.jmxremote
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.port=7199
      - -Dcom.sun.management.jmxremote.ssl=false
    environment:
      REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: repository-search-elastic-index
      REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: "9200"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
    expose:
      - "7199"
    depends_on:
      - repository-search-elastic-index
      - repository-service

  repository-service:
    environment:
      REPOSITORY_SEARCH_ELASTIC_INDEX_HOST: repository-search-elastic-index
      REPOSITORY_SEARCH_ELASTIC_INDEX_PORT: "9200"
    depends_on:
      - repository-search-elastic-index

volumes:
  repository-search-elastic-index-volume: